### PR TITLE
Transition to EasyReflectometry

### PR DESCRIPTION
**Pull request by arm61**
After a lot of dead ends, I think this is the transition we want

### CODE REVIEW

**Comment by rozyczko** [comment]
Any advice for when we will do the same transition in easyDiffraction -> EasyDiffraction ?

**Comment by arm61** [comment]
Lots once I get it right 😢

**Comment by arm61** [comment]
@rozyczko the change to line 36 here seems to be the crux of things https://github.com/easyScience/EasyReflectometryApp/pull/68/files#diff-de88810c8197896c2221da309b3128b214579aa07b9b4b92226fdb616f5a5084

**Comment by arm61** [comment]
All the tests pass. Lets merge to develop and see how we did

**Pull request merged**
