### PR TITLE
Loading of comma and tab separated 3 column ascii files

### LINKED ISSUE #94: Can't load data
Trying to load a .dat file in csv format using the `Import data from local drive` button, nothing appears to happen and no data is loaded. Data looks like:
image
[60_61.txt](https://github.com/easyScience/EasyReflectometryApp/files/9685605/60_61.txt)
changed extension to `.txt` to upload here

### PR DESCRIPTION
**Pull request by jfkcooper**
This fixes #94 by trying to load 3 column ascii files both with tab and comma separators. No tests added, but can be written if required.

### CODE REVIEW

**Comment by arm61** [comment]
I changed the base to `develop` instead of `main`. Will look at this first thing tomorrow morning. I suggest that I write the test afterward (I suspect this is good practice so that we actually test what we think we are testing you know?)

**Comment by jfkcooper** [comment]
Yeah, this is much neater

**Comment by arm61** [comment]
Does it run successfully?

**Comment by jfkcooper** [comment]
yes, though I dont have 4 column data to hand to test it, can you send me some?

**Comment by arm61** [comment]
Additionally can you rebase against the latest develop

```
git fetch upstream
git rebase upstream/develop
git push
```

(I think) 

This will let the tests run.

**Pull request merged**
